# ИсклĀùениā и нĀансý работý с ними
## ИсклĀùениā (Exception)

### Определениā, обûаā информаøиā

ИсклĀùение (exception) – собýтие, ознаùаĀûее, ùто в программе ùто-то поúло не так (возникла оúибка) 

Вýброситþ (проброситþ) исклĀùение – вýзватþ собýтие исклĀùениā Некоторýе ситуаøии возникновениā исклĀùений:

● Поделили на нолþ
● Аргумент функøии некорректнýй
● Доступ к полĀ неиниøиализированного обüекта
● Вýход за граниøý массива

Где могут поāвитþсā:
● Во времā вýполнениā .NET Runtime (доступ к пустому обüекту)
● ВýбрасýваĀтсā сторонними библиотеками
● ВýзýваĀтсā полþзователем принудителþно

### Как вýглāдāт?

```C#
var a = 0;
var b = 4; 
Console.WriteLine(b/a);
```

[img](https://github.com/IlyaGall/C-/blob/main/52%20%D0%98%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B8%20%D0%BD%D1%8E%D0%B0%D0%BD%D1%81%D1%8B%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D1%81%20%D0%BD%D0%B8%D0%BC%D0%B8/img/1.JPG)

### ИсклĀùениā и управление состоāнием

Конструируā тип (Классý) мý заранее представлāем ситуаøии в которýх он будет исполþзоватþсā. В каùестве имен суûествителþнýе. Затем определāĀтсā свойства собýтиā, методý и тп . Форма определениā ÿтих ùленов становитсā интерфейсом типа. Именно ùленý определāĀт допустимýе действиā с типом и его ÿкземплāрами. Если ùлен сборки не может реúитþ возложеннуĀ на него задаùу программа вýбрасýвает исклĀùение.

```C#
internal seald class Account{
    public static
    void Transfer(Account from, Account to, Decimal amount)
    {
        form-=amount;
        to+-amount;
    }
}
```


### Механизм обработки исклĀùений


```C#
private void SomeMethod()
{
    try
    {
        //Код, требующиий корректноно восстановления
        //или очистки ресурсов
    }
    catch(InvalidOperationException)
    {
        // Код восстановления работоспособности
        //после InvalidOperationException
    }
    catch(IOException)
    {
        // Код восстановления работоспособности
        //после IOException
    }
    catch{
        // Код восстановления работоспособности после всех остальных исключений
        // После прехвата исключений их обчно генерируют повторно
        //Рассмотрим эту тему позже
        throw;
    }
    finally
    {
        //Здесь находится код, выполняющий очистку ресурсов
        //после операций начатых в блоке try. Этот код
        //выполняется ВСЕГДА вне зависимости от наличия исключения
        //Код, следующий за блоком finally, выполняется, если в блоке
    }

    //не генерировалось исключение или если исключение было перехвачено
    //блоком catch, а новое не генерировалось
}
```

### CLS-совместимýе и CLS-несовместимýе исклĀùениā

[img](https://github.com/IlyaGall/C-/blob/main/52%20%D0%98%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B8%20%D0%BD%D1%8E%D0%B0%D0%BD%D1%81%D1%8B%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D1%81%20%D0%BD%D0%B8%D0%BC%D0%B8/img/2.JPG)


```C#
private void SomeMethod()
{
    try
    {
        // Код, требующиий корректноно восстановления
        // или очистки ресурсов
    }
    catch(Exception e)
    {
        //    До C# 2.0 этот блок перехватывал только CLS-совместимые исключения
        // В С# это блок научился перехватывать также
        // CLS- несовместимые исключения
    }
    catch
    {
        // Во всех версия C# данный блок перехватывает
        // и совместимые, и не совместимые с CLS исключения
        throw; // повторная генерация прехваченного исключения
    }
}
```

## Как работатþ с исклĀùением
### System.Exception

System.Exception – базовýй класс исклĀùений Все исклĀùениā наследуĀтсā на определенном уровне от
System.Exception
Принāто все классý
исклĀùений назýватþ с
суффиксом Exception
• InvalidOperationException
• OutOfRangeException
• ArgumentNullException

[img](https://github.com/IlyaGall/C-/blob/main/52%20%D0%98%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B8%20%D0%BD%D1%8E%D0%B0%D0%BD%D1%81%D1%8B%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D1%81%20%D0%BD%D0%B8%D0%BC%D0%B8/img/3.JPG)

### Иерархиā исклĀùений

[img](https://github.com/IlyaGall/C-/blob/main/52%20%D0%98%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%B8%20%D0%BD%D1%8E%D0%B0%D0%BD%D1%81%D1%8B%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B%20%D1%81%20%D0%BD%D0%B8%D0%BC%D0%B8/img/4.JPG)
    
### Генераøиā собственнýх исклĀùений

```C#
///<summary>
///Мое собственное исключение
///</summary>
class MyCystomException:Exception
{

}
```

### Вариантý перехвата
● try catch
● try catch finally
● AppDomain.CurrentDomain.UnhandledException
● Application.ThreadException (WinForms, WPF)

### Stacktrace
● Содержит цепочку вызовов методов до места, где произошло исключение (с точностью номера строки)
● Можно получить и Environment.StackTrace
● Можно использовать System.Diagnostic.StackTrace

## Операторý

### Обûее, синтаксис

```C#
try
{
    if (b == 0)
    {
        throw new DivideByZeroException("Делим на ноль");
    }
    return a / b;
}
catch (Exception e)
{
     Console.WriteLine("Произошла ошибка");
     return 0.0;

}
finally
{
    Console.WriteLine("Я блок finally ");
}
```

### throw– оператор вýзова исклĀùениā

```C#
try
{
    if (b == 0)
    {
        throw new DivideByZeroException("Делим на ноль");
    }
    return a / b;
}
catch (Exception e)
{
    Console.WriteLine("Произошла ошибка"); 
    return 0.0;

}
finally
{
    Console.WriteLine("Я блок finally ");
}
```

Синтаксис
```
throw объект_класс_exception_или_производного
```

### throw , вариантý исполþзованиā

Можно так:

```throw new Exception("Я сообщение об ошибке");```

А можно так:
```C#
var ex = new Exception("Я cообщение о6 ошибке"); 
ex.Data.Add("a", "2");
throw ex;
```

### try\catch

```C#
try
{
    if (b == 0)
    {
        throw new DivideByZeroException("Делим на ноль");
    }
    return a / b;
    
}
catch (Exception e)
{
    Console.WriteLine("Произошла ошибка"); 
    return 0.0;
}
finally
{
    Console.WriteLine("Я блок finally ");
}
```

### try catch

* try catch – операторý перехвата исклĀùений
* try {} – обüāвлāет областþ кода, где потенøиалþно может вýбрасýватþсā исклĀùение
* catch{} – «ловит» исклĀùение из блока try и обрабатýвает даннуĀ ситуаøиĀ

Синтаксис:

```C#
try
{
    // Здесь может быть какой-то код
}
catch (Exception exc)
{
    // А здесь происходит обработка исключения ехс
    // вызванного в каком-то коде
}
```



















